spring:
  # 默认开发环境
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallbackToSystemLocale: true
  jmx:
    enabled: false
  # thymeleaf
  thymeleaf:
    prefix: classpath:/thymeleaf/
    check-template-location: true
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML5
  # 静态文件
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations[0]: classpath:/static/
  #  用于数据库表结构版本管理
  flyway:
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jackson:
    serialization:
      write-dates-as-timestamps: true

chat2db:
  version: 1.0.0

# flywaydb 输出执行sql的日志
logging:
  level:
    org:
      flywaydb: debug
    ai:
      chat2db:
        server:
          domain:
            repository:
              mapper: debug

chatgpt:
  apiKey: sk-xxxx
  apiHost: https://api.openai.com/
  # 可以选择GPT3或GPT35
  version: GPT35
  context:
    length: 1

# Print the HTTP log
logbook:
  include:
    - /api/**
#server:
#  undertow:
#    io-threads: 8
#    worker-threads: 200
#    buffer-size: 1024
#    direct-buffers: true
#    max-http-post-size: 0

